### PR TITLE
Added Aur Instructions

### PR DESCRIPTION
**Pull request by niksingh710**
For Arch Linux users.
A few extra lines have been changed as prettier has performed formatting.

### CODE REVIEW

**Comment by trimclain** [comment]
Hi, thanks for the PR!
Wanted to let you know, that you have mixed spaces with tabs in your [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=getnf).  
I also wouldn't probably change the filetype in the modeline, since it's actually a shell script and vim detects it correclty.

**Comment by trimclain** [comment]
Could you also remove the formatting added by prettier? We don't really like their choices for markdown.

**Comment by niksingh710** [comment]
@trimclain I fixed the prettier formatting for the README.
And thanks for mentioning the mix-up of spaces with tabs in `PKGBUILD` fixed that also.

Unable to understand what you meant by?
>  I also wouldn't probably change the filetype in the modeline, since it's actually a shell script and vim detects it correclty.

**Comment by niksingh710** [comment]
Aah, now I got it you meant modeline for the last line in comment 
```
# vim: ft=PKGBUILD
```
The filetype `PKGBUILD` was there because of `pkgbuild-language-server`.
I checked it now, and it has been deprecated in favor of keeping `PKGBUILD` shell file.
so would be removing that also.

Anything else you feel needs to be changed please mention.

**Comment by trimclain** [comment]
LGTM, thanks

**Review by trimclain — APPROVED** [review]

**Pull request merged**
