### PR TITLE
adding flag to update getnf to the latest version

### PR DESCRIPTION
**Pull request by arnavgr**
Fixes [#56]

### CODE REVIEW

**Comment by trimclain** [comment]
Hi, thanks for the PR. We're still not sure if we want to add the ability to update `getnf` itself (especially since it's just running a one-liner). It's not really that common for a program to update itself, it's usually the job for the package manager or the user.
And we definitely don't want to change any existing flags.

**Comment by arnavgr** [comment]
> Hi, thanks for the PR. We're still not sure if we want to add the ability to update `getnf` itself (especially since it's just running a one-liner). It's not really that common for a program to update itself, it's usually the job for the package manager or the user. And we definitely don't want to change any existing flags.

sure you can change the update flag to something else and keep the original the same, but i feel adding an update is really simple as i dont always have to go to github, copy the installation command and paste it everytime i want to update it

**Comment by ronniedroid** [comment]
Yeah, I agree that the tool should not manage itself, it is the job of the package manager or the user to keep the tool updated.

I am working on a Go version that hopefully will be in all major distros package managers.

**Comment by arnavgr** [comment]
Fair enough

**Pull request closed without merging**
