### PR TITLE
adding termux support to getnf

### PR DESCRIPTION
**Pull request by arnavgr**
This adds additional functionality to install and apply fonts on termux(native linux terminal on android)

### CODE REVIEW

**Comment by arnavgr** [comment]
Is there anything you want me to change in this?

**Comment by trimclain** [comment]
Hi, thanks for the PR. Besides wrong formatting, in its current form, your code doesn't fit in with the rest. I need some time to figure out a solution

**Comment by arnavgr** [comment]
Okay, thanks

**Comment by arnavgr** [comment]
You could let me know if u want me to change this in a specific order or how I could make it fit with the rest, like maybe only activating the function if --termux argument is used or something on those lines

**Comment by trimclain** [comment]
As far as I understand, your goal is to allow setting the currently used font in Termux. While it is interesting and could probably be used to create a separate tool, it doesn't align with the core idea behind `getnf`, which is to download Nerd Fonts and make them available on your system. Setting the font is left to the user and is different for every app.

**Comment by arnavgr** [comment]
I understand, it's just that applying the installed fonts is a pain in termux, giving the user the option to apply the installed font is much better since it's not as simple as selecting the installed fonts from lxappearance or editing gtk.conf , but I understand if this can't be merged I'll maintain this seperately

**Pull request closed without merging**
